# Generated by Django 6.0.4 on 2026-04-17 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_department_options_alter_employee_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leavebalance',
            name='casual_leave',
            field=models.DecimalField(decimal_places=1, default=100, max_digits=5),
        ),
        migrations.AlterField(
            model_name='leavebalance',
            name='earned_leave',
            field=models.DecimalField(decimal_places=1, default=100, max_digits=5),
        ),
        migrations.AlterField(
            model_name='leavebalance',
            name='sick_leave',
            field=models.DecimalField(decimal_places=1, default=100, max_digits=5),
        ),
        migrations.AlterField(
            model_name='leavebalance',
            name='work_from_home',
            field=models.DecimalField(decimal_places=1, default=200, max_digits=5),
        ),
    ]
