# Generated by Django 6.0.3 on 2026-04-06 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_order_order_number_order_phone_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pet_age',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='pet_breed',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='warranty',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
