# Generated by Django 6.0.3 on 2026-04-02 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_phone_number_alter_user_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(default='temp_default_phone', max_length=15, unique=True),
            preserve_default=False,
        ),
    ]
